# Generated by Django 5.2.7 on 2025-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('name', 'birth_date', 'died_date'), name='unique_author_name_birth_date'),
        ),
    ]
