# Generated by Django 5.2.7 on 2025-11-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fiction', 'Художественная литература'), ('textbook', 'Учебник'), ('other', 'Другое')], max_length=20)),
                ('publisher', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_app.author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'constraints': [models.UniqueConstraint(fields=('title', 'author', 'publication_year', 'publisher'), name='unique_book')],
            },
        ),
    ]
